[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"

[server]
runOnSave = true
enableCORS = false

[browser]
gatherUsageStats = false
